In [ ]:
print("Analysis of Student Grades")

In [ ]:
print("Looks like fun!")

In [1]:
from pathlib import Path

In [6]:
base_dir = Path.cwd()
csv_path  = base_dir/"student_grades.csv"

In [3]:
import pandas as pd#imports pandas package and gives it an alias of pd

In [7]:
#call the read_csv function (pandas)
#load the content of the csv file into a dataframe(df)
#a dataframe is a 2 dimensional view of the csv file
grades = pd.read_csv(csv_path)

In [8]:
grades.head()#shows the first 5 rows of a dataframe

      Name    Class  Grade
0    Alice     Math     88
1      Bob     Math     92
2  Charlie  Science     85
3     Dana     Math     76
4      Eli  Science     90

In [9]:
grades.info()#print a summary of dataframe info

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Class   5 non-null      str
 2   Grade   5 non-null      int64
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [10]:
grades.shape #how many rows and columns

(5, 3)

In [11]:
grades.describe()#summary statisics of numeric columns

          Grade
count   5.00000
mean   86.20000
std     6.26099
min    76.00000
25%    85.00000
50%    88.00000
75%    90.00000
max    92.00000

In [12]:
grades["Class"].unique()#unique values in that column

<StringArray>
['Math', 'Science']
Length: 2, dtype: str

In [17]:
#show only the math records
math_grades = grades[grades["Class"] == "Math"]
math_grades

    Name Class  Grade
0  Alice  Math     88
1    Bob  Math     92
3   Dana  Math     76

In [18]:
#count of math students
math_grades.shape[0]

3

In [19]:
#sort dataframe highest to lowest grade of math grades
top_math = math_grades.sort_values(by = "Grade", ascending = False)
top_math

    Name Class  Grade
1    Bob  Math     92
0  Alice  Math     88
3   Dana  Math     76

In [20]:
#Top math student
top_math.iloc[0]

Name      Bob
Class    Math
Grade      92
Name: 1, dtype: object

In [ ]:
#Exercise!
#get the science grades and display them
#Sort the science grades from highest to lowest
#Display the row with the highest science grade